export const trending = [
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
        genre_ids: [28, 12, 53],
        id: 497698,
        original_language: "en",
        original_title: "Black Widow",
        poster_path: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
        video: false,
        vote_average: 8.4,
        overview:
          "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
        release_date: "2021-07-07",
        vote_count: 1211,
        title: "Black Widow",
        popularity: 2548.641,
        media_type: "movie",
      },
      {
        original_title: "The Tomorrow War",
        poster_path: "/xipF6XqfSYV8DxLqfLN6aWlwuRp.jpg",
        video: false,
        id: 588228,
        overview:
          "The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.",
        release_date: "2021-07-02",
        vote_count: 1925,
        adult: false,
        backdrop_path: "/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg",
        vote_average: 8.4,
        genre_ids: [28, 878],
        title: "The Tomorrow War",
        original_language: "en",
        popularity: 6694.868,
        media_type: "movie",
      },
      {
        original_title: "A Quiet Place Part II",
        poster_path: "/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg",
        id: 520763,
        overview:
          "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.",
        release_date: "2021-05-21",
        vote_count: 1579,
        vote_average: 7.8,
        adult: false,
        backdrop_path: "/z2UtGA1WggESspi6KOXeo66lvLx.jpg",
        video: false,
        genre_ids: [878, 53, 27],
        title: "A Quiet Place Part II",
        original_language: "en",
        popularity: 2167.964,
        media_type: "movie",
      },
      {
        vote_average: 8.2,
        overview:
          "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat.",
        original_name: "Loki",
        origin_country: ["US"],
        backdrop_path: "/wr7nrzDrpGCEgYnw15jyAB59PtZ.jpg",
        genre_ids: [18, 10765],
        vote_count: 5573,
        original_language: "en",
        poster_path: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
        name: "Loki",
        id: 84958,
        first_air_date: "2021-06-09",
        popularity: 5335.93,
        media_type: "tv",
      },
      {
        poster_path: "/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
        video: false,
        vote_average: 8.1,
        overview:
          "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
        release_date: "2021-06-17",
        vote_count: 2448,
        adult: false,
        backdrop_path: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
        title: "Luca",
        id: 508943,
        genre_ids: [16, 35, 10751, 14],
        original_language: "en",
        original_title: "Luca",
        popularity: 4393.272,
        media_type: "movie",
      },
      {
        video: false,
        vote_average: 6.8,
        overview:
          "In 1994, a group of teenagers discovers that the terrifying events which have haunted their town for generations ​are all connected — and that they may be the next targets.",
        release_date: "2021-06-28",
        vote_count: 351,
        adult: false,
        backdrop_path: "/5C8bfwglg91uZhc2fbfpSjNGamV.jpg",
        title: "Fear Street Part One: 1994",
        genre_ids: [27, 9648],
        id: 591273,
        original_language: "en",
        original_title: "Fear Street Part One: 1994",
        poster_path: "/9J9Wy39ZjrVmfk7yMkulpcI5sy0.jpg",
        popularity: 1073.052,
        media_type: "movie",
      },
      {
        vote_average: 8,
        overview:
          "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
        release_date: "2021-07-01",
        adult: false,
        backdrop_path: "/gX5UrH1TLVVBwI7WxplW43BD6Z1.jpg",
        vote_count: 414,
        genre_ids: [16, 35, 12, 10751],
        id: 459151,
        original_language: "en",
        original_title: "The Boss Baby: Family Business",
        poster_path: "/5dExO5G2iaaTxYnLIFKLWofDzyI.jpg",
        title: "The Boss Baby: Family Business",
        video: false,
        popularity: 4927.181,
        media_type: "movie",
      },
      {
        poster_path: "/dbPKu7GrA0bDzwaKv7RxpXyU2bU.jpg",
        id: 591274,
        video: false,
        title: "Fear Street Part Two: 1978",
        overview:
          "In 1978, two rival groups at Camp Nightwing must band together to solve a terrifying mystery when horrors from their towns' history come alive.",
        release_date: "2021-07-09",
        adult: false,
        backdrop_path: "/fdkDp9BCttm2QKNQDyj0ZdojHE4.jpg",
        vote_count: 145,
        genre_ids: [27, 9648],
        vote_average: 7.4,
        original_language: "en",
        original_title: "Fear Street Part Two: 1978",
        popularity: 541.328,
        media_type: "movie",
      },
      {
        genre_ids: [16, 10765, 10759],
        original_language: "en",
        poster_path: "/wWwTjKER5a8LRUGHrw86VU0gUy1.jpg",
        name: "RESIDENT EVIL: Infinite Darkness",
        first_air_date: "2021-07-08",
        vote_count: 123,
        overview:
          "Years after the horrors Raccoon City, Leon and Claire find themselves consumed by a dark conspiracy when a viral attack ravages the White House.",
        vote_average: 8.1,
        id: 110642,
        original_name: "RESIDENT EVIL: Infinite Darkness",
        origin_country: ["US"],
        backdrop_path: "/uPHXbrh9jlq2XgfjjTFlkJfgtOQ.jpg",
        popularity: 221.735,
        media_type: "tv",
      },
      {
        overview:
          "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
        release_date: "2021-05-19",
        adult: false,
        backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
        genre_ids: [28, 12, 80, 53],
        vote_count: 480,
        original_language: "en",
        original_title: "F9",
        poster_path: "/qIicLxr7B7gIt5hxZxo423BJLlK.jpg",
        title: "F9",
        id: 385128,
        vote_average: 7.7,
        video: false,
        popularity: 2661.97,
        media_type: "movie",
      },
      {
        poster_path: "/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg",
        id: 423108,
        video: false,
        title: "The Conjuring: The Devil Made Me Do It",
        overview:
          "Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
        release_date: "2021-05-25",
        adult: false,
        backdrop_path: "/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg",
        vote_count: 2956,
        genre_ids: [27, 9648, 53],
        vote_average: 8,
        original_language: "en",
        original_title: "The Conjuring: The Devil Made Me Do It",
        popularity: 1425.857,
        media_type: "movie",
      },
      {
        overview:
          "A group of criminals are brought together under mysterious circumstances and have to work together to uncover what's really going on when their simple job goes completely sideways.",
        release_date: "2021-06-24",
        adult: false,
        backdrop_path: "/ok7RdHhVngnwkvKj09tvtOvypG.jpg",
        title: "No Sudden Move",
        genre_ids: [80, 18, 53, 9648],
        vote_count: 65,
        original_language: "en",
        original_title: "No Sudden Move",
        id: 649409,
        poster_path: "/34BmdJkdvRweC3xJJFlOFQ2IbYc.jpg",
        video: false,
        vote_average: 6.8,
        popularity: 397.018,
        media_type: "movie",
      },
      {
        original_title: "Cruella",
        poster_path: "/rTh4K5uw9HypmpGslcKd4QfHl93.jpg",
        id: 337404,
        overview:
          "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
        release_date: "2021-05-26",
        vote_count: 3890,
        vote_average: 8.5,
        adult: false,
        backdrop_path: "/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg",
        video: false,
        genre_ids: [35, 80],
        title: "Cruella",
        original_language: "en",
        popularity: 2054.954,
        media_type: "movie",
      },
      {
        original_language: "en",
        original_title: "Peter Rabbit 2: The Runaway",
        poster_path: "/cycDz68DtTjJrDJ1fV8EBq2Xdpb.jpg",
        video: false,
        vote_average: 7.4,
        overview:
          "Bea, Thomas, and the rabbits have created a makeshift family, but despite his best efforts, Peter can’t seem to shake his mischievous reputation. Adventuring out of the garden, Peter finds himself in a world where his mischief is appreciated, but when his family risks everything to come looking for him, Peter must figure out what kind of bunny he wants to be.",
        release_date: "2021-03-25",
        vote_count: 123,
        title: "Peter Rabbit 2: The Runaway",
        adult: false,
        backdrop_path: "/5HjzYTihkH7EvOWSE7KcsF6pBMM.jpg",
        id: 522478,
        genre_ids: [10751, 35, 12, 16, 14],
        popularity: 2491.766,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/bjIPzixuWnOzxDG25WaXKuy9lYZ.jpg",
        genre_ids: [28, 35, 53],
        id: 522931,
        original_language: "en",
        original_title: "Hitman's Wife's Bodyguard",
        poster_path: "/6zwGWDpY8Zu0L6W4SYWERBR8Msw.jpg",
        video: false,
        vote_average: 7.2,
        overview:
          "The world’s most lethal odd couple – bodyguard Michael Bryce and hitman Darius Kincaid – are back on another life-threatening mission. Still unlicensed and under scrutiny, Bryce is forced into action by Darius's even more volatile wife, the infamous international con artist Sonia Kincaid. As Bryce is driven over the edge by his two most dangerous protectees, the trio get in over their heads in a global plot and soon find that they are all that stand between Europe and a vengeful and powerful madman.",
        release_date: "2021-06-14",
        vote_count: 152,
        title: "Hitman's Wife's Bodyguard",
        popularity: 266.798,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/5MlvT4DZIdkpb7A9t375HVoiJ1v.jpg",
        genre_ids: [28, 53],
        vote_count: 308,
        original_language: "en",
        original_title: "The Ice Road",
        poster_path: "/pj6UQPrtmC0snzPeU1HUhGWTgz6.jpg",
        video: false,
        id: 646207,
        vote_average: 7.4,
        title: "The Ice Road",
        overview:
          "After a remote diamond mine collapses in far northern Canada, an ice road driver must lead an impossible rescue mission over a frozen ocean to save the trapped miners.",
        release_date: "2021-06-24",
        popularity: 157.88,
        media_type: "movie",
      },
      {
        vote_average: 8,
        overview:
          "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
        release_date: "2021-03-24",
        adult: false,
        backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
        vote_count: 6314,
        genre_ids: [14, 12, 28],
        id: 399566,
        original_language: "en",
        original_title: "Godzilla vs. Kong",
        poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
        title: "Godzilla vs. Kong",
        video: false,
        popularity: 1095.877,
        media_type: "movie",
      },
      {
        backdrop_path: "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
        title: "Mortal Kombat",
        genre_ids: [28, 14, 12],
        original_language: "en",
        original_title: "Mortal Kombat",
        poster_path: "/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg",
        video: false,
        vote_average: 7.5,
        overview:
          "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
        release_date: "2021-04-07",
        vote_count: 3247,
        id: 460465,
        adult: false,
        popularity: 1211.539,
        media_type: "movie",
      },
      {
        video: false,
        vote_average: 7.1,
        overview:
          "After a romantic evening at their secluded lake house, a woman wakes up handcuffed to her dead husband. Trapped and isolated in the dead of winter, she must fight off hired killers to escape her late spouse's twisted plan.",
        id: 672741,
        adult: false,
        backdrop_path: "/6jEiWUxDsRS6o7ayhLbaJKVVAjq.jpg",
        vote_count: 52,
        genre_ids: [27, 53],
        release_date: "2021-07-01",
        original_language: "en",
        original_title: "Till Death",
        poster_path: "/sTPGfWghOGL7HnUhV5QFFWBaHbV.jpg",
        title: "Till Death",
        popularity: 85.519,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/pVNXmfZvQKFdUKVYNJxZAiy69DC.jpg",
        genre_ids: [28, 12],
        id: 529106,
        original_language: "ru",
        original_title: "Майор Гром: Чумной Доктор",
        overview:
          "Igor Grom is a skilled policeman from St. Petersburg, known for his daring nature and uncompromising attitude towards the criminals of all kinds. Incredible strength, analytical mind and integrity – these qualities make Major Grom the perfect policeman. Working tirelessly, he always pushes through, and meets the challenges standing in the way.",
        poster_path: "/wnesEmcq7xdw1Rm1Bn6XEFTkenR.jpg",
        release_date: "2021-04-01",
        title: "Major Grom: Plague Doctor",
        video: false,
        vote_average: 7.3,
        vote_count: 70,
        popularity: 51.554,
        media_type: "movie",
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
];

export const netflixOriginals = [
  {
    page: 1,
    results: [
      {
        backdrop_path: "/9nBVkNBe4x9HKDAzxjxlIqecxCW.jpg",
        first_air_date: "2021-06-25",
        genre_ids: [35, 18],
        id: 126280,
        name: "Sex/Life",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Sex/Life",
        overview:
          "A woman's daring sexual past collides with her married-with-kids present when the bad-boy ex she can't stop fantasizing about crashes back into her life.",
        popularity: 1705.876,
        poster_path: "/2ST6l4WP7ZfqAetuttBqx8F3AAH.jpg",
        vote_average: 7.3,
        vote_count: 274,
      },
      {
        backdrop_path: "/pMkjcQEdqSlVSjngH5TLEBS2TN.jpg",
        first_air_date: "2018-10-05",
        genre_ids: [80, 9648, 18],
        id: 76669,
        name: "Elite",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Élite",
        overview:
          "When three working class kids enroll in the most exclusive school in Spain, the clash between the wealthy and the poor students leads to tragedy.",
        popularity: 1050.171,
        poster_path: "/3NTAbAiao4JLzFQw6YxP1YZppM8.jpg",
        vote_average: 8.2,
        vote_count: 7217,
      },
      {
        backdrop_path: "/h48Dpb7ljv8WQvVdyFWVLz64h4G.jpg",
        first_air_date: "2016-01-25",
        genre_ids: [80, 10765],
        id: 63174,
        name: "Lucifer",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Lucifer",
        overview:
          "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
        popularity: 907.568,
        poster_path: "/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg",
        vote_average: 8.5,
        vote_count: 9521,
      },
      {
        backdrop_path: "/8GjdLwzbfr5fnIvXAZHe11fcIJO.jpg",
        first_air_date: "2021-06-30",
        genre_ids: [18],
        id: 126386,
        name: "Somos.",
        origin_country: ["MX"],
        original_language: "es",
        original_name: "Somos.",
        overview:
          "The lives of the people of Allende, a Mexican border town, are overtaken by a powerful cartel's operations, leading to tragedy. Inspired by true events.",
        popularity: 518.336,
        poster_path: "/opHopqkLzkftwUl4jTLcwckjuu.jpg",
        vote_average: 7.8,
        vote_count: 48,
      },
      {
        backdrop_path: "/iq5L971DFW1SwLJdvl7OpPI1QeZ.jpg",
        first_air_date: "2021-06-17",
        genre_ids: [16, 10759, 10765],
        id: 114868,
        name: "Record of Ragnarok",
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "終末のワルキューレ",
        overview:
          "Before eradicating humankind from the world, the gods give them one last chance to prove themselves worthy of survival. Let the Ragnarok battles begin.",
        popularity: 463.101,
        poster_path: "/kTs2WNZOukpWdNhoRlH94pSJ3xf.jpg",
        vote_average: 8.8,
        vote_count: 516,
      },
      {
        backdrop_path: "/y0zAjgCghA8XXMk5O7rIJMybXBt.jpg",
        first_air_date: "2021-06-04",
        genre_ids: [18, 10765],
        id: 103768,
        name: "Sweet Tooth",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Sweet Tooth",
        overview:
          "On a perilous adventure across a post-apocalyptic world, a lovable boy who's half-human and half-deer searches for a new beginning with a gruff protector.",
        popularity: 418.685,
        poster_path: "/rgMfhcrVZjuy5b7Pn0KzCRCEnMX.jpg",
        vote_average: 8,
        vote_count: 589,
      },
      {
        backdrop_path: "/wu444tM9YBllq9UcBv5TeidO3j3.jpg",
        first_air_date: "2020-01-31",
        genre_ids: [10765, 18, 9648],
        id: 91557,
        name: "Ragnarok",
        origin_country: ["NO"],
        original_language: "no",
        original_name: "Ragnarok",
        overview:
          "A small Norwegian town experiencing warm winters and violent downpours seems to be headed for another Ragnarök -- unless someone intervenes in time.",
        popularity: 400.761,
        poster_path: "/xUtOM1QO4r8w8yeE00QvBdq58N5.jpg",
        vote_average: 8.1,
        vote_count: 509,
      },
      {
        backdrop_path: "/mF25LlPgSek0Wgv6NUKSlzLLQBQ.jpg",
        first_air_date: "2021-06-17",
        genre_ids: [18, 9648, 10765],
        id: 104157,
        name: "Katla",
        origin_country: ["IS"],
        original_language: "is",
        original_name: "Katla",
        overview:
          "A year after a subglacial volcano erupts, mysterious elements from prehistoric times emerge from the melting ice, bringing unforeseen consequences.",
        popularity: 351.644,
        poster_path: "/vRPDQP51i1Z2RuoIQaxVSj7Pd5R.jpg",
        vote_average: 7.1,
        vote_count: 93,
      },
      {
        backdrop_path: "/gL8myjGc2qrmqVosyGm5CWTir9A.jpg",
        first_air_date: "2018-05-02",
        genre_ids: [10759, 18],
        id: 77169,
        name: "Cobra Kai",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Cobra Kai",
        overview:
          "This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
        popularity: 284.144,
        poster_path: "/4CkQvdUAtoLW3qkjWi7t1MTnW7R.jpg",
        vote_average: 8.1,
        vote_count: 3284,
      },
      {
        backdrop_path: "/lucFMV4qxvpsti5xnN6paUxCbAn.jpg",
        first_air_date: "2021-06-17",
        genre_ids: [18],
        id: 126525,
        name: "Elite Short Stories: Carla Samuel",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Elite Histórias Breves: Carla Samuel",
        overview:
          "Samuel attempts a big, romantic gesture at the airport in order to persuade Carla not to board her flight to London.",
        popularity: 255.925,
        poster_path: "/onPkMMtzcJs9A6vKljNBa3ujI8g.jpg",
        vote_average: 7.8,
        vote_count: 176,
      },
      {
        backdrop_path: "/rcA17r3hfHtRrk3Xs3hXrgGeSGT.jpg",
        first_air_date: "2016-07-15",
        genre_ids: [10765, 9648, 18],
        id: 66732,
        name: "Stranger Things",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Stranger Things",
        overview:
          "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
        popularity: 245.243,
        poster_path: "/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
        vote_average: 8.6,
        vote_count: 8509,
      },
      {
        backdrop_path: "/tU7JWx4ouMae7LVdrhS43hGn4Yt.jpg",
        first_air_date: "2021-03-24",
        genre_ids: [18, 80, 9648],
        id: 120168,
        name: "Who Killed Sara?",
        origin_country: ["MX"],
        original_language: "es",
        original_name: "¿Quién mató a Sara?",
        overview:
          "Hell-bent on exacting revenge and proving he was framed for his sister's murder, Álex sets out to unearth much more than the crime's real culprit.",
        popularity: 222.832,
        poster_path: "/o7uk5ChRt3quPIv8PcvPfzyXdMw.jpg",
        vote_average: 7.7,
        vote_count: 854,
      },
      {
        backdrop_path: "/uPHXbrh9jlq2XgfjjTFlkJfgtOQ.jpg",
        first_air_date: "2021-07-08",
        genre_ids: [16, 10765, 10759],
        id: 110642,
        name: "RESIDENT EVIL: Infinite Darkness",
        origin_country: ["US"],
        original_language: "en",
        original_name: "RESIDENT EVIL: Infinite Darkness",
        overview:
          "Years after the horrors Raccoon City, Leon and Claire find themselves consumed by a dark conspiracy when a viral attack ravages the White House.",
        popularity: 221.735,
        poster_path: "/wWwTjKER5a8LRUGHrw86VU0gUy1.jpg",
        vote_average: 8.1,
        vote_count: 123,
      },
      {
        backdrop_path: "/ro2nKGja5KHPNFxvmI2QsEU9Y4E.jpg",
        first_air_date: "2021-01-08",
        genre_ids: [80, 18, 9648],
        id: 96677,
        name: "Lupin",
        origin_country: ["FR"],
        original_language: "fr",
        original_name: "Lupin",
        overview:
          "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.",
        popularity: 220.577,
        poster_path: "/sgxawbFB5Vi5OkPWQLNfl3dvkNJ.jpg",
        vote_average: 7.9,
        vote_count: 1037,
      },
      {
        backdrop_path: "/esMo90QAVfOpSVTUiCuhmDTnc5y.jpg",
        first_air_date: "2021-07-01",
        genre_ids: [18],
        id: 125910,
        name: "Young Royals",
        origin_country: ["SE"],
        original_language: "sv",
        original_name: "Young Royals",
        overview:
          "Prince Wilhelm adjusts to life at his prestigious new boarding school, Hillerska, but following his heart proves more challenging than anticipated.",
        popularity: 217.375,
        poster_path: "/6CHznbr0BF78ar16zJwTVRYLLOX.jpg",
        vote_average: 9.5,
        vote_count: 120,
      },
      {
        backdrop_path: "/9OkuEgUebqBFJKyQu9cxUd4dd4B.jpg",
        first_air_date: "2017-08-11",
        genre_ids: [18, 35],
        id: 71578,
        name: "Atypical",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Atypical",
        overview:
          "Sam, an 18-year-old on the autism spectrum, takes a funny, yet painful, journey of self-discovery for love and independence and upends his family.",
        popularity: 204.042,
        poster_path: "/iZ10Q7bEBP5bYD8DpKIbsRxdpeC.jpg",
        vote_average: 8.4,
        vote_count: 485,
      },
      {
        backdrop_path: "/qJxzjUjCpTPvDHldNnlbRC4OqEh.jpg",
        first_air_date: "2019-02-15",
        genre_ids: [10759, 10765, 18],
        id: 75006,
        name: "The Umbrella Academy",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Umbrella Academy",
        overview:
          "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.",
        popularity: 185.9,
        poster_path: "/scZlQQYnDVlnpxFTxaIv2g0BWnL.jpg",
        vote_average: 8.7,
        vote_count: 7049,
      },
      {
        backdrop_path: "/e9vUuy3y69vfzjuMWPCauhXs8Kq.jpg",
        first_air_date: "2021-06-14",
        genre_ids: [18, 80],
        id: 126531,
        name: "Elite Short Stories: Guzmán Caye Rebe",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Elite Histórias Breves: Guzmán Caye Rebe",
        overview:
          "Rebe hosts an intimate house warming party for her friends, but the situation takes a dramatic turn with the help of drugs and unexpected visitors.",
        popularity: 179.208,
        poster_path: "/4Y3jaO9schbo32WB2fGQv1en8ZB.jpg",
        vote_average: 8.4,
        vote_count: 211,
      },
      {
        backdrop_path: "/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg",
        first_air_date: "2017-05-02",
        genre_ids: [80, 18],
        id: 71446,
        name: "Money Heist",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "La casa de papel",
        overview:
          "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
        popularity: 175.596,
        poster_path: "/MoEKaPFHABtA1xKoOteirGaHl1.jpg",
        vote_average: 8.3,
        vote_count: 13276,
      },
      {
        backdrop_path: "/61m8HGEWwE4q8oSz3AY5vl5F3BS.jpg",
        first_air_date: "2019-01-11",
        genre_ids: [35, 18],
        id: 81356,
        name: "Sex Education",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Sex Education",
        overview:
          "Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.",
        popularity: 174.949,
        poster_path: "/4Bph0hhnDH6dpc0SZIV522bLm4P.jpg",
        vote_average: 8.3,
        vote_count: 3872,
      },
    ],
    total_pages: 60,
    total_results: 1183,
  },
];

export const topRated = [
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/gNBCvtYyGPbjPCT1k3MvJuNuXR6.jpg",
        genre_ids: [35, 18, 10749],
        id: 19404,
        original_language: "hi",
        original_title: "दिलवाले दुल्हनिया ले जायेंगे",
        overview:
          "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
        popularity: 17.849,
        poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
        release_date: "1995-10-20",
        title: "Dilwale Dulhania Le Jayenge",
        video: false,
        vote_average: 8.7,
        vote_count: 3011,
      },
      {
        adult: false,
        backdrop_path: "/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg",
        genre_ids: [18, 80],
        id: 278,
        original_language: "en",
        original_title: "The Shawshank Redemption",
        overview:
          "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        popularity: 50.397,
        poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        release_date: "1994-09-23",
        title: "The Shawshank Redemption",
        video: false,
        vote_average: 8.7,
        vote_count: 19210,
      },
      {
        adult: false,
        backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
        genre_ids: [10749],
        id: 724089,
        original_language: "en",
        original_title: "Gabriel's Inferno Part II",
        overview:
          "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
        popularity: 6.571,
        poster_path: "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
        release_date: "2020-07-31",
        title: "Gabriel's Inferno Part II",
        video: false,
        vote_average: 8.7,
        vote_count: 1278,
      },
      {
        adult: false,
        backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
        genre_ids: [18, 80],
        id: 238,
        original_language: "en",
        original_title: "The Godfather",
        overview:
          "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
        popularity: 45.439,
        poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        release_date: "1972-03-14",
        title: "The Godfather",
        video: false,
        vote_average: 8.7,
        vote_count: 14499,
      },
      {
        adult: false,
        backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
        genre_ids: [10749, 35],
        id: 761053,
        original_language: "en",
        original_title: "Gabriel's Inferno Part III",
        overview:
          "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
        popularity: 17.254,
        poster_path: "/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
        release_date: "2020-11-19",
        title: "Gabriel's Inferno Part III",
        video: false,
        vote_average: 8.7,
        vote_count: 839,
      },
      {
        adult: false,
        backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
        genre_ids: [10749],
        id: 696374,
        original_language: "en",
        original_title: "Gabriel's Inferno",
        overview:
          "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
        popularity: 8.137,
        poster_path: "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
        release_date: "2020-05-29",
        title: "Gabriel's Inferno",
        video: false,
        vote_average: 8.6,
        vote_count: 2072,
      },
      {
        adult: false,
        backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
        genre_ids: [18, 36, 10752],
        id: 424,
        original_language: "en",
        original_title: "Schindler's List",
        overview:
          "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
        popularity: 26.863,
        poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        release_date: "1993-11-30",
        title: "Schindler's List",
        video: false,
        vote_average: 8.6,
        vote_count: 11540,
      },
      {
        adult: false,
        backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
        genre_ids: [18, 80],
        id: 240,
        original_language: "en",
        original_title: "The Godfather: Part II",
        overview:
          "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
        popularity: 30.918,
        poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        release_date: "1974-12-20",
        title: "The Godfather: Part II",
        video: false,
        vote_average: 8.6,
        vote_count: 8672,
      },
      {
        adult: false,
        backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
        genre_ids: [10749, 16, 18],
        id: 372058,
        original_language: "ja",
        original_title: "君の名は。",
        overview:
          "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
        popularity: 119.671,
        poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
        release_date: "2016-08-26",
        title: "Your Name.",
        video: false,
        vote_average: 8.6,
        vote_count: 7622,
      },
      {
        adult: false,
        backdrop_path: "/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
        genre_ids: [16, 10751, 14],
        id: 129,
        original_language: "ja",
        original_title: "千と千尋の神隠し",
        overview:
          "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        popularity: 75.456,
        poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        release_date: "2001-07-20",
        title: "Spirited Away",
        video: false,
        vote_average: 8.5,
        vote_count: 11520,
      },
      {
        adult: false,
        backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
        genre_ids: [35, 53, 18],
        id: 496243,
        original_language: "ko",
        original_title: "기생충",
        overview:
          "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        popularity: 105.463,
        poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        release_date: "2019-05-30",
        title: "Parasite",
        video: false,
        vote_average: 8.5,
        vote_count: 11678,
      },
      {
        adult: false,
        backdrop_path: "/9guoVF7zayiiUq5ulKQpt375VIy.jpg",
        genre_ids: [16, 28, 14, 12],
        id: 592350,
        original_language: "ja",
        original_title:
          "僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング",
        overview:
          "Class 1-A visits Nabu Island where they finally get to do some real hero work. The place is so peaceful that it's more like a vacation … until they're attacked by a villain with an unfathomable Quirk! His power is eerily familiar, and it looks like Shigaraki had a hand in the plan. But with All Might retired and citizens' lives on the line, there's no time for questions. Deku and his friends are the next generation of heroes, and they're the island's only hope.",
        popularity: 353.496,
        poster_path: "/zGVbrulkupqpbwgiNedkJPyQum4.jpg",
        release_date: "2019-12-20",
        title: "My Hero Academia: Heroes Rising",
        video: false,
        vote_average: 8.5,
        vote_count: 749,
      },
      {
        adult: false,
        backdrop_path: "/hQQTE285UQB1lLY1XiioQ77LYnC.jpg",
        genre_ids: [16, 35, 10749, 18, 14],
        id: 572154,
        original_language: "ja",
        original_title: "青春ブタ野郎はゆめみる少女の夢を見ない",
        overview:
          "In Fujisawa, Sakuta Azusagawa is in his second year of high school. Blissful days with his girlfriend and upperclassman, Mai Sakurajima, are interrupted by the appearance of his first crush, Shoko Makinohara.",
        popularity: 143.77,
        poster_path: "/7Ai8vNEv4zEveh12JViGikoVPVV.jpg",
        release_date: "2019-06-15",
        title: "Rascal Does Not Dream of a Dreaming Girl",
        video: false,
        vote_average: 8.5,
        vote_count: 281,
      },
      {
        adult: false,
        backdrop_path: "/5Nz25DPXfQaSpDgce42Y3kFg9G4.jpg",
        genre_ids: [14, 18, 80],
        id: 497,
        original_language: "en",
        original_title: "The Green Mile",
        overview:
          "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        popularity: 60.734,
        poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
        release_date: "1999-12-10",
        title: "The Green Mile",
        video: false,
        vote_average: 8.5,
        vote_count: 12463,
      },
      {
        adult: false,
        backdrop_path: "/yHtB4KHNigx3ZoxDvQbW2SOXGfq.jpg",
        genre_ids: [16, 10751, 12, 14],
        id: 441130,
        original_language: "en",
        original_title: "Wolfwalkers",
        overview:
          "In a time of superstition and magic, when wolves are seen as demonic and nature an evil to be tamed, a young apprentice hunter comes to Ireland with her father to wipe out the last pack. But when she saves a wild native girl, their friendship leads her to discover the world of the Wolfwalkers and transform her into the very thing her father is tasked to destroy.",
        popularity: 22.818,
        poster_path: "/uRkDrsKwCCZC9zdHZs2CFTt1ATZ.jpg",
        release_date: "2020-10-26",
        title: "Wolfwalkers",
        video: false,
        vote_average: 8.5,
        vote_count: 492,
      },
      {
        adult: false,
        backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
        genre_ids: [18],
        id: 389,
        original_language: "en",
        original_title: "12 Angry Men",
        overview:
          "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
        popularity: 22.059,
        poster_path: "/7sf9CgJz30aXDvrg7DYYUQ2U91T.jpg",
        release_date: "1957-04-10",
        title: "12 Angry Men",
        video: false,
        vote_average: 8.5,
        vote_count: 5669,
      },
      {
        adult: false,
        backdrop_path: "/1fOsyhVz5qyX2rl1qqX6KImVhTx.jpg",
        genre_ids: [18, 35],
        id: 644479,
        original_language: "es",
        original_title: "Dedicada a mi ex",
        overview:
          "The film tells the story of Ariel, a 21-year-old who decides to form a rock band to compete for a prize of ten thousand dollars in a musical band contest, this as a last option when trying to get money to save their relationship and reunite with his ex-girlfriend, which breaks due to the trip she must make to Finland for an internship. Ariel with her friend Ortega, decides to make a casting to find the other members of the band, although they do not know nothing about music, thus forming a band with members that have diverse and opposite personalities.",
        popularity: 21.783,
        poster_path: "/riAooJrFvVhotyaOgoI0WR7okSe.jpg",
        release_date: "2019-11-01",
        title: "Dedicated to my ex",
        video: false,
        vote_average: 8.5,
        vote_count: 398,
      },
      {
        adult: false,
        backdrop_path: "/88J6waYVTta8Qz3iX3qUeWNA5d5.jpg",
        genre_ids: [18, 10749],
        id: 447362,
        original_language: "en",
        original_title: "Life in a Year",
        overview:
          "A 17 year old finds out that his girlfriend is dying, so he sets out to give her an entire life, in the last year she has left.",
        popularity: 93.567,
        poster_path: "/bP7u19opmHXYeTCUwGjlLldmUMc.jpg",
        release_date: "2020-11-27",
        title: "Life in a Year",
        video: false,
        vote_average: 8.5,
        vote_count: 695,
      },
      {
        adult: false,
        backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
        genre_ids: [53, 80],
        id: 680,
        original_language: "en",
        original_title: "Pulp Fiction",
        overview:
          "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        popularity: 48.649,
        poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        release_date: "1994-09-10",
        title: "Pulp Fiction",
        video: false,
        vote_average: 8.5,
        vote_count: 21360,
      },
      {
        adult: false,
        backdrop_path: "/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
        genre_ids: [12, 35],
        id: 40096,
        original_language: "pt",
        original_title: "O Auto da Compadecida",
        overview:
          "The lively Jack the Cricket and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.",
        popularity: 7.875,
        poster_path: "/m8eFedsS7vQCZCS8WGp5n1bVD0q.jpg",
        release_date: "2000-09-15",
        title: "A Dog's Will",
        video: false,
        vote_average: 8.5,
        vote_count: 786,
      },
    ],
    total_pages: 445,
    total_results: 8884,
  },
];

export const comedyMovies = [
  {
    page: 1,
    results: [
      {
        backdrop_path: "/9nBVkNBe4x9HKDAzxjxlIqecxCW.jpg",
        first_air_date: "2021-06-25",
        genre_ids: [35, 18],
        id: 126280,
        name: "Sex/Life",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Sex/Life",
        overview:
          "A woman's daring sexual past collides with her married-with-kids present when the bad-boy ex she can't stop fantasizing about crashes back into her life.",
        popularity: 1705.876,
        poster_path: "/2ST6l4WP7ZfqAetuttBqx8F3AAH.jpg",
        vote_average: 7.3,
        vote_count: 274,
      },
      {
        backdrop_path: "/A9sCKnxgTTapzu307ybdXCJQEqD.jpg",
        first_air_date: "2013-12-02",
        genre_ids: [16, 35, 10765, 10759],
        id: 60625,
        name: "Rick and Morty",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Rick and Morty",
        overview:
          "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
        popularity: 1369.521,
        poster_path: "/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg",
        vote_average: 8.8,
        vote_count: 4784,
      },
      {
        backdrop_path: "/5b5ZZGECl4FLDBKn3zJ6w6GBPRg.jpg",
        first_air_date: "2021-06-17",
        genre_ids: [35, 18],
        id: 119243,
        name: "iCarly",
        origin_country: ["US"],
        original_language: "en",
        original_name: "iCarly",
        overview:
          "Ten years after signing off of one of TV's most iconic shows, Carly, Spencer, and Freddie are back, navigating the next chapter of their lives, facing the uncertainties of life in their twenties.",
        popularity: 944.551,
        poster_path: "/s5k4GqTUGXeUdScNrjpYfiQLKHI.jpg",
        vote_average: 7.8,
        vote_count: 313,
      },
      {
        backdrop_path: "/hpU2cHC9tk90hswCFEpf5AtbqoL.jpg",
        first_air_date: "1989-12-17",
        genre_ids: [10751, 16, 35, 18],
        id: 456,
        name: "The Simpsons",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Simpsons",
        overview:
          "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
        popularity: 427.37,
        poster_path: "/zLudbPueg8CxGhMS2tyDh3p0TdK.jpg",
        vote_average: 7.9,
        vote_count: 6768,
      },
      {
        backdrop_path: "/h3vViR087OJlk4PedNt5JLIKOOi.jpg",
        first_air_date: "2004-11-16",
        genre_ids: [18, 35, 9648],
        id: 1408,
        name: "House",
        origin_country: ["US"],
        original_language: "en",
        original_name: "House",
        overview:
          "Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.",
        popularity: 323.873,
        poster_path: "/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg",
        vote_average: 8.6,
        vote_count: 3725,
      },
      {
        backdrop_path: "/2O3ZRECju00Jod6LrVB3uRgZMXK.jpg",
        first_air_date: "2021-07-07",
        genre_ids: [10751, 35, 16],
        id: 90461,
        name: "Monsters at Work",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Monsters at Work",
        overview:
          "Six months after the events of Monsters, Inc., the city of Monstropolis is now fueled with the sound of laughter. Tylor Tuskmon, a mechanic on the Facilities Team, dreams of working alongside his idols Mike Wazowski and James P. 'Sulley' Sullivan.",
        popularity: 273.399,
        poster_path: "/s2L0tGpnWJMfaX1y0xUFcfKyX9p.jpg",
        vote_average: 7.3,
        vote_count: 240,
      },
      {
        backdrop_path: "/dI4BnzgBj05mm61qWU4cpPSU1D3.jpg",
        first_air_date: "2021-02-16",
        genre_ids: [35],
        id: 97754,
        name: "Young Rock",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Young Rock",
        overview:
          "As Dwayne Johnson runs for president in 2032, he takes a comedic look back at his extraordinary life through the outrageous stories of his family and youth that shaped him into the man he is today. He explores his childhood years living amid influential wrestling icons while his dad rose to fame in the business, his rebellious teenage years attending high school in Pennsylvania, and his football years teamed up with powerhouse players at the University of Miami. In his telling, Johnson explains that while his experiences have been larger than life, he remains a down-to-earth guy who still relates to the American people.",
        popularity: 260.028,
        poster_path: "/hUmSMg5KHJkgeOk9AvbTINYOuEf.jpg",
        vote_average: 7.1,
        vote_count: 146,
      },
      {
        backdrop_path: "/sVmEr2z1kD2H5lhi4G9qQoVLLsD.jpg",
        first_air_date: "2020-07-08",
        genre_ids: [18, 35],
        id: 104877,
        name: "You Knock on My Door",
        origin_country: ["TR"],
        original_language: "tr",
        original_name: "Sen Çal Kapımı",
        overview:
          "Connecting all her hopes in her life to her education, Eda comes face to face with Serkan Bolat, who unknowingly cuts her scholarship abroad and caused her to remain a high school graduate. Serkan Bolat offers to give Eda her scholarship back if she pretends to be engaged to him for two months. Eda first rejects the offer due to her hatred for him, but when circumstances change, she has no choice but to accept the offer. While pretending to be engaged, Serkan and Eda begin to have a passionate, challenging relationship that will make you forget all they know right, because love is hard. And that's why it's amazing!!",
        popularity: 259.751,
        poster_path: "/nzBenFJ2D2MCWTwTt2uc4BGWLtA.jpg",
        vote_average: 8.1,
        vote_count: 850,
      },
      {
        backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
        first_air_date: "1994-09-22",
        genre_ids: [35, 18],
        id: 1668,
        name: "Friends",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Friends",
        overview:
          "The misadventures of a group of friends as they navigate the pitfalls of work, life and love in Manhattan.",
        popularity: 230.266,
        poster_path: "/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
        vote_average: 8.4,
        vote_count: 4759,
      },
      {
        backdrop_path: "/bhtvmyFHLBhmoUoo3evgsfjCTAs.jpg",
        first_air_date: "2021-04-16",
        genre_ids: [10751, 35, 18],
        id: 96716,
        name: "Big Shot",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Big Shot",
        overview:
          "After getting ousted from his job in the NCAA for throwing a chair at a referee, a hothead men’s basketball coach Marvyn Korn must take a job at Westbrook School for Girls, a private all-girls high school, in an effort to redeem what's left of his career and reputation.",
        popularity: 228.692,
        poster_path: "/42bFOkD1eBDjyqn0uHSyAYuL2qv.jpg",
        vote_average: 8.2,
        vote_count: 199,
      },
      {
        backdrop_path: "/1D3sDadfGOsYEjZT8N2V2MeGcTN.jpg",
        first_air_date: "2004-10-04",
        genre_ids: [35, 10766, 18],
        id: 12637,
        name: "Rebelde",
        origin_country: ["MX"],
        original_language: "es",
        original_name: "Rebelde",
        overview:
          "The series is set at the Elite Way School, a prestigious private boarding high school in Mexico City with a major plot line revolving around a group of students forming a pop band. Additional subplots involve the school's faculty and the students' parents. One trademark of the show is the random use of English words and phrases, often used by fresa characters.",
        popularity: 212.71,
        poster_path: "/iehrrb9CmYCiV1hXp5pdGQQmGNe.jpg",
        vote_average: 8.5,
        vote_count: 4004,
      },
      {
        backdrop_path: "/jqBNii1Qv1W4khVzRtdy7ONOroq.jpg",
        first_air_date: "2021-05-27",
        genre_ids: [16, 35, 10762],
        id: 124920,
        name: "Rugrats",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Rugrats",
        overview:
          "A reinvention of the beloved 90s cartoon, Rugrats follows a group of adventurous babies as they discover the big world around them. Lead by Tommy Pickles, this toddler crew explores the world from their pint-sized and wildly imaginative perspective.",
        popularity: 204.909,
        poster_path: "/1kMDkkX9LctUUtJPvJPVKW9ylBW.jpg",
        vote_average: 7.6,
        vote_count: 47,
      },
      {
        backdrop_path: "/7uihCghJiyYFTXSh1BOPdHQN8xK.jpg",
        first_air_date: "1997-08-13",
        genre_ids: [35, 16],
        id: 2190,
        name: "South Park",
        origin_country: ["US"],
        original_language: "en",
        original_name: "South Park",
        overview:
          "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.",
        popularity: 204.806,
        poster_path: "/iiCY2QIGSnmtVkIdjkKAfwDs0KF.jpg",
        vote_average: 8.2,
        vote_count: 2450,
      },
      {
        backdrop_path: "/9OkuEgUebqBFJKyQu9cxUd4dd4B.jpg",
        first_air_date: "2017-08-11",
        genre_ids: [18, 35],
        id: 71578,
        name: "Atypical",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Atypical",
        overview:
          "Sam, an 18-year-old on the autism spectrum, takes a funny, yet painful, journey of self-discovery for love and independence and upends his family.",
        popularity: 204.042,
        poster_path: "/iZ10Q7bEBP5bYD8DpKIbsRxdpeC.jpg",
        vote_average: 8.4,
        vote_count: 485,
      },
      {
        backdrop_path: "/jbTqU6BJMufoMnPSlO4ThrcXs3Y.jpg",
        first_air_date: "1999-01-31",
        genre_ids: [16, 35],
        id: 1434,
        name: "Family Guy",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Family Guy",
        overview:
          "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
        popularity: 200.684,
        poster_path: "/eWWCRjBfLyePh2tfZdvNcIvKSJe.jpg",
        vote_average: 7,
        vote_count: 2847,
      },
      {
        backdrop_path: "/gHoE5UByMIjbhBnbYxezrCVGwCL.jpg",
        first_air_date: "2005-12-27",
        genre_ids: [10762, 16, 10759, 35],
        id: 4686,
        name: "Ben 10",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Ben 10",
        overview:
          "When 10-year-old Ben Tennyson discovers a mysterious device, he gains the power to change into ten different alien heroes, each with uniquely awesome powers. With such abilities at his disposal, Ben realizes a greater responsibility to help others and stop evildoers, but that doesn't mean he's above a little superpowered mischief now and then.",
        popularity: 190.751,
        poster_path: "/pT0NlYVIkwM2zAw9oUkePwrOlxW.jpg",
        vote_average: 8.1,
        vote_count: 1005,
      },
      {
        backdrop_path: "/rHuXgDmrv4vMKgQZ6pu2E2iLJnM.jpg",
        first_air_date: "2010-07-11",
        genre_ids: [35, 10764],
        id: 33238,
        name: "Running Man",
        origin_country: ["KR"],
        original_language: "ko",
        original_name: "런닝맨",
        overview:
          "These days, variety entertainment is gradually disappearing. It is one of Korea's representative variety entertainment shows that has been in charge of Sunday evenings for over 10 years. In this program, many stars and members play games and missions together. It is characterized by going around several places. In particular, this program focuses solely on laughter among the many fun elements of entertainment.\n\nOpen your eyes! Big fun enters!\n\nOpen your mouth!  A big smile enters!\n\nOpen your mind! Instructive lesson enters!",
        popularity: 188.035,
        poster_path: "/2Wmmu1MkqxJ48J7aySET9EKEjXz.jpg",
        vote_average: 8.4,
        vote_count: 110,
      },
      {
        backdrop_path: "/6KsfFlAtRbfWgF8S5LI8nVErtSp.jpg",
        first_air_date: "2019-11-12",
        genre_ids: [10751, 35, 18],
        id: 85801,
        name: "High School Musical: The Musical: The Series",
        origin_country: ["US"],
        original_language: "en",
        original_name: "High School Musical: The Musical: The Series",
        overview:
          "A group of East High students countdown to the opening night of their school’s first-ever production of “High School Musical.” Showmances blossom; friendships are tested while new ones are made; rivalries flare and lives are changed forever as these young people discover the transformative power that only a high school drama club can provide.",
        popularity: 183.323,
        poster_path: "/9S3BS5oS9a8sNiTWuZi9aveE4bR.jpg",
        vote_average: 8.1,
        vote_count: 613,
      },
      {
        backdrop_path: "/61m8HGEWwE4q8oSz3AY5vl5F3BS.jpg",
        first_air_date: "2019-01-11",
        genre_ids: [35, 18],
        id: 81356,
        name: "Sex Education",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Sex Education",
        overview:
          "Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.",
        popularity: 174.949,
        poster_path: "/4Bph0hhnDH6dpc0SZIV522bLm4P.jpg",
        vote_average: 8.3,
        vote_count: 3872,
      },
      {
        backdrop_path: "/bhF63Jd90gRYyTHd4y5GCGA2vX6.jpg",
        first_air_date: "2010-09-06",
        genre_ids: [16, 35],
        id: 31132,
        name: "Regular Show",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Regular Show",
        overview:
          "Two bored groundskeepers, Mordecai (a six-foot-tall blue jay) and Rigby (a hyperactive raccoon) are best friends who spend their days trying to entertain themselves by any means necessary, much to the displeasure of their boss. Their everyday pursuits often lead to things spiraling out of control and into the surreal.",
        popularity: 173.022,
        poster_path: "/88dAGv0ywrLJKCynkH226dBwe0i.jpg",
        vote_average: 8.8,
        vote_count: 1154,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  },
];

export const documentaries = [
  {
    page: 1,
    results: [
      {
        backdrop_path: "/18ybGiTcKVnXCYCAmVBIIy8CNhx.jpg",
        first_air_date: "2019-10-18",
        genre_ids: [99],
        id: 94667,
        name: "Traveling with the Derbez",
        origin_country: ["MX"],
        original_language: "es",
        original_name: "De viaje con los Derbez",
        overview:
          "The series revolves around the Derbez family on their trip to Morocco, the family is made up of Eugenio Derbez, the patriarch of the family, Alessandra Rosaldo, his wife, Aitana Derbez, their daughter, Vadhir and José Eduardo Derbez, their children, and Aislinn Derbez, his eldest daughter. , along with Mauricio Ochmann and his daughter Kailani.",
        popularity: 100.205,
        poster_path: "/o1lAdiCYmCuDb25wyBCJQMeUhVA.jpg",
        vote_average: 7.5,
        vote_count: 1131,
      },
      {
        backdrop_path: null,
        first_air_date: "1978-06-02",
        genre_ids: [10763, 99],
        id: 2035,
        name: "20/20",
        origin_country: ["US"],
        original_language: "en",
        original_name: "20/20",
        overview:
          "20/20 is an American television newsmagazine that has been broadcast on ABC since June 6, 1978. Created by ABC News executive Roone Arledge, the show was designed similarly to CBS's 60 Minutes but focuses more on human interest stories than international and political subjects. The program's name derives from the \"20/20\" measurement of visual acuity.\n\nThe hour-long program has been a staple on Friday evenings for much of the time since it moved to that timeslot from Thursdays in September 1987, though special editions of the program occasionally air on other nights.",
        popularity: 68.055,
        poster_path: "/fzmAv0KRBYGWwENLM3NaRjwHgkQ.jpg",
        vote_average: 7,
        vote_count: 15,
      },
      {
        backdrop_path: "/AhcPiOviZ36mE5DjkX3aI9zIQJ9.jpg",
        first_air_date: "2002-10-21",
        genre_ids: [99],
        id: 45,
        name: "Top Gear",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Top Gear",
        overview:
          'This fast-paced and stunt-filled motor show tests whether cars, both mundane and extraordinary, live up to their manufacturers\' claims. The long-running show travels to locations around the world, performing extreme stunts and challenges to see what the featured cars are capable of doing. The current hosts are Paddy Mcguinness, Chris Harris and Andrew "Freddie" Flintoff.',
        popularity: 64.323,
        poster_path: "/aqM6QnuhSXzjHlKbXyKUqxaGiWu.jpg",
        vote_average: 7.3,
        vote_count: 471,
      },
      {
        backdrop_path: "/epQEpsbNHrEe76oSI42TOwHKOLF.jpg",
        first_air_date: "2021-02-24",
        genre_ids: [99, 10768],
        id: 93736,
        name: "Age of Samurai: Battle for Japan",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Age of Samurai: Battle for Japan",
        overview:
          "Dynamic reenactments and expert commentaries bring to life the tumultuous history and power struggles of a warring 16th-century feudal Japan.",
        popularity: 50.854,
        poster_path: "/wIKQRtc2kKiBmBnkOjjvMqIDfah.jpg",
        vote_average: 7,
        vote_count: 190,
      },
      {
        backdrop_path: "/xJqcoi8hi3yFCl05oULKtmfSDXi.jpg",
        first_air_date: "1974-03-03",
        genre_ids: [99],
        id: 3562,
        name: "NOVA",
        origin_country: ["US"],
        original_language: "en",
        original_name: "NOVA",
        overview:
          "PBS' premier science series helps viewers of all ages explore the science behind the headlines. Along the way, NOVA demystifies science and technology, and highlights the people involved in scientific pursuits.",
        popularity: 48.826,
        poster_path: "/giUBXYnDAaJgNqA6iE3BMVE2EHp.jpg",
        vote_average: 7.1,
        vote_count: 71,
      },
      {
        backdrop_path: null,
        first_air_date: "2017-01-31",
        genre_ids: [99, 18],
        id: 69998,
        name: "Hugo Chávez, El Comandante",
        origin_country: ["CO", "US", "VE"],
        original_language: "es",
        original_name: "Hugo Chávez, El Comandante",
        overview:
          "The life of Hugo Chavez; from childhood, his arrival to power, confrontations, and loves to his last days as president.",
        popularity: 45.852,
        poster_path: "/sEThDZHGrhD6UPDVnP7skTAa6mF.jpg",
        vote_average: 7.1,
        vote_count: 347,
      },
      {
        backdrop_path: "/qqewE3aUi1js0tVvrhWT3znQppY.jpg",
        first_air_date: "2003-09-03",
        genre_ids: [99, 18],
        id: 90,
        name: "Mayday",
        origin_country: ["CA"],
        original_language: "en",
        original_name: "Mayday",
        overview:
          "Revealing the dark truth that aviation safety improves one crash at a time, Mayday  investigates legendary aviation disasters to find out what went wrong and why.\n\nBased on cockpit voice recorders, accident reports and eyewitness accounts, every episode also features interviews, state-of-the-art CGI and gripping reenactments.",
        popularity: 45.808,
        poster_path: "/dTTl7DR23zr8IlPSMh2Vcfumyo3.jpg",
        vote_average: 8.1,
        vote_count: 154,
      },
      {
        backdrop_path: "/eRJN9V7CRM68xtYGMHJgsDl4wkZ.jpg",
        first_air_date: "2021-05-31",
        genre_ids: [99],
        id: 118454,
        name: "Breaking Bobby Bones",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Breaking Bobby Bones",
        overview:
          "Bobby Bones crisscrosses the country to meet everyday heroes who have extraordinary jobs, hobbies and abilities, welcoming him with open arms to give him a crash course in their specialized skills.",
        popularity: 45.247,
        poster_path: "/hukCREjIdma7dRQ9J0qbPRSb8eD.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        backdrop_path: "/9aKLfKx3QDGdzGuLw4GJDKtxsF0.jpg",
        first_air_date: "2021-07-09",
        genre_ids: [99],
        id: 127626,
        name: "How to Become a Tyrant",
        origin_country: ["US"],
        original_language: "en",
        original_name: "How to Become a Tyrant",
        overview:
          "To govern with an iron fist, it is necessary to know very well the game of absolute power, as shown by the infamous dictators presented in this documentary series.",
        popularity: 45.159,
        poster_path: "/kdWrvDC6ApgZL9HxDVYTXwtHZkM.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        backdrop_path: "/v3WopDdgHCoNvoBS0V8eVJdurJP.jpg",
        first_air_date: "1971-01-28",
        genre_ids: [35, 99, 18],
        id: 10029,
        name: "Great Performances",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Great Performances",
        overview:
          "The best in the performing arts from across America and around the world including a diverse programming portfolio of classical music, opera, popular song, musical theater, dance, drama, and performance documentaries.",
        popularity: 44.657,
        poster_path: "/4WS9naGSt9ZaFgdsP2HDZkqXWDh.jpg",
        vote_average: 6.8,
        vote_count: 6,
      },
      {
        backdrop_path: "/41ZBU34r8WqCBSczUzL7SMQAgX3.jpg",
        first_air_date: "2021-02-10",
        genre_ids: [99, 80, 9648],
        id: 116989,
        name: "Crime Scene: The Vanishing at the Cecil Hotel",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Crime Scene: The Vanishing at the Cecil Hotel",
        overview:
          "The notorious Cecil Hotel grows in infamy when guest Elisa Lam vanishes. A dive into crime's darkest places.",
        popularity: 44.163,
        poster_path: "/2JECBiHk8U8PIhswVd3Pthc13tG.jpg",
        vote_average: 7.3,
        vote_count: 193,
      },
      {
        backdrop_path: "/9XhJ6rsGX2bG0CBNFWwzjtPaZig.jpg",
        first_air_date: "2019-03-08",
        genre_ids: [99],
        id: 87083,
        name: "Formula 1: Drive to Survive",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Formula 1: Drive to Survive",
        overview:
          "Drivers, managers and team owners live life in the fast lane -- both on and off the track -- during one cutthroat season of Formula 1 racing.",
        popularity: 42.247,
        poster_path: "/hZZpqv9bKo9tUMmQY54HIJcgyqx.jpg",
        vote_average: 8.3,
        vote_count: 89,
      },
      {
        backdrop_path: "/dDoO1nKuBUB3rjrR54grbQ5CvEG.jpg",
        first_air_date: "1983-01-17",
        genre_ids: [99, 10763, 10767],
        id: 4384,
        name: "Frontline",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Frontline",
        overview:
          "Since it began in 1983, Frontline has been airing public-affairs documentaries that explore a wide scope of the complex human experience. Frontline's goal is to extend the impact of the documentary beyond its initial broadcast by serving as a catalyst for change.",
        popularity: 41.268,
        poster_path: "/m4kZVMJC9P9BI7T0F5fUMWyelcA.jpg",
        vote_average: 7.7,
        vote_count: 24,
      },
      {
        backdrop_path: "/6GdneIKJFjv5ArM5b6kKJQ4o8z4.jpg",
        first_air_date: "2008-12-29",
        genre_ids: [99],
        id: 27240,
        name: "Seven Deadly Sins",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Seven Deadly Sins",
        overview:
          "The series traces the history of the seven deadly sins, how they became part of religious doctrine, and looks at historical figures who have been the worst perpetrators of each. Each of the seven sins is explored, from their origins and nature, their opposing virtue, and their corresponding punishment.",
        popularity: 39.878,
        poster_path: "/u7UUYOeMcQ62qHhRhWeGO09h8qH.jpg",
        vote_average: 7.8,
        vote_count: 2018,
      },
      {
        backdrop_path: "/gs3CZfP8Sq7TwUEGLqU7buBa6lU.jpg",
        first_air_date: "2014-03-09",
        genre_ids: [99],
        id: 58474,
        name: "Cosmos",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Cosmos",
        overview:
          "Famed astrophysicist Neil deGrasse Tyson provides clarity for the vision of the cosmos as he voyages across the universe with never-before-told stories that delve into the scientific concepts of the laws of gravity and the origins of space and time.",
        popularity: 39.761,
        poster_path: "/5o07ps0QZ0bNoRYxTn9cPdRWlUu.jpg",
        vote_average: 8.3,
        vote_count: 993,
      },
      {
        backdrop_path: "/zL8kXiImDSHFfridtcvFw5ai9NB.jpg",
        first_air_date: "1982-10-10",
        genre_ids: [99, 10751],
        id: 14951,
        name: "Nature",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Nature",
        overview:
          "Consistently stunning documentaries transport viewers to far-flung locations ranging from the torrid African plains to the chilly splendours of icy Antarctica. The show's primary focus is on animals and ecosystems around the world. A comic book based on the show, meant to be used an as educational tool for kids, was briefly distributed to museums and schools at no cost in the mid-2000s.",
        popularity: 36.298,
        poster_path: "/mniuxYgwoNJpmOI2eXpm4hYK7wi.jpg",
        vote_average: 8.1,
        vote_count: 18,
      },
      {
        backdrop_path: "/xysWPglQNT6HcGvz6KogX4Hhx7K.jpg",
        first_air_date: "1964-02-04",
        genre_ids: [99],
        id: 1966,
        name: "Horizon",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Horizon",
        overview:
          "Horizon tells amazing science stories, unravels mysteries and reveals worlds you've never seen before.",
        popularity: 34.441,
        poster_path: "/uX8pic7asQBdnwMB9QjPvTsn1Dw.jpg",
        vote_average: 7.6,
        vote_count: 18,
      },
      {
        backdrop_path: "/4V82tQmK98SJoq2DuRkH6O8YTwf.jpg",
        first_air_date: "2019-06-14",
        genre_ids: [99],
        id: 91862,
        name: "Sex Life",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Sex Life",
        overview:
          "A voyeuristic documentary series about titillating sexual and erotic experiences.",
        popularity: 33.716,
        poster_path: "/q9qSnMSrSl45rbuSViXmwgoWdCP.jpg",
        vote_average: 6.9,
        vote_count: 7,
      },
      {
        backdrop_path: "/2eSo388uW5wRNsWhjl1cyrwaufP.jpg",
        first_air_date: "2021-07-08",
        genre_ids: [99, 80],
        id: 127617,
        name: "Elize Matsunaga: Once Upon a Crime",
        origin_country: [],
        original_language: "pt",
        original_name: "Elize Matsunaga: Era uma Vez um Crime",
        overview:
          "The crime shocked Brazil: Elize Matsunaga shot and dismembered her rich husband. Featuring her first interview, this docuseries dives deep into the case.",
        popularity: 32.503,
        poster_path: "/30bzZ1exfrPXi5UkpfNIIMGYVzp.jpg",
        vote_average: 7,
        vote_count: 1,
      },
      {
        backdrop_path: "/xgNeRVuzDl3qaDnFo0n2MGsbUDO.jpg",
        first_air_date: "2019-07-21",
        genre_ids: [99],
        id: 91405,
        name: "Gordon Ramsay: Uncharted",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Gordon Ramsay: Uncharted",
        overview:
          "Follow Gordon Ramsay as he meets with indigenous people around the globe to learn about the cultures, dishes and flavors unique to each location. Each episode concludes with Ramsay challenging himself with a local food legend by his side - putting his newfound skills to the test as they cook a feast together for the natives.",
        popularity: 31.766,
        poster_path: "/bh8xg3j9lG0oaNd76Xrad03hqoP.jpg",
        vote_average: 8.2,
        vote_count: 18,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  },
];
